config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Warm up"
    - duration: 120
      arrivalRate: 10
      rampTo: 50
      name: "Ramp up load"
    - duration: 300
      arrivalRate: 50
      name: "Sustained load"
  payload:
    path: "./test-data.csv"
    fields:
      - "townSlug"
      - "personSlug"
  variables:
    townSlugs:
      - "borrego-springs"
      - "mendocino"
      - "pismo-beach"
      - "lake-elsinore"
  plugins:
    metrics-by-endpoint: {}
    expect: {}
  processor: "./processor.js"

scenarios:
  - name: "Homepage Visit"
    weight: 20
    flow:
      - get:
          url: "/"
          expect:
            - statusCode: 200
            - contentType: "text/html"
            - hasHeader: "cache-control"
      - think: 3

  - name: "Browse Towns"
    weight: 30
    flow:
      - get:
          url: "/"
      - think: 2
      - get:
          url: "/{{ $randomString(townSlugs) }}"
          expect:
            - statusCode: 200
      - think: 5

  - name: "Search for Person"
    weight: 25
    flow:
      - get:
          url: "/"
      - think: 2
      - get:
          url: "/{{ townSlug }}"
          expect:
            - statusCode: 200
      - think: 3
      - get:
          url: "/{{ townSlug }}/{{ personSlug }}"
          expect:
            - statusCode: 200
      - think: 5

  - name: "Support Flow"
    weight: 15
    flow:
      - get:
          url: "/"
      - think: 2
      - get:
          url: "/show-your-support"
          expect:
            - statusCode: 200
      - think: 3
      - get:
          url: "/learn-more"
          expect:
            - statusCode: 200

  - name: "Information Seeker"
    weight: 10
    flow:
      - get:
          url: "/learn-more"
          expect:
            - statusCode: 200
      - think: 10
      - get:
          url: "/code-of-conduct"
          expect:
            - statusCode: 200
      - think: 5
      - get:
          url: "/privacy-policy"
          expect:
            - statusCode: 200